dubbo:
  application:
    name: view-web
  registry:
    address: zookeeper://192.168.140.129:2181

server:
  port: 8090
spring:
  application:
    name: search-web
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
